# Generated by Django 4.0.5 on 2022-06-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('prioridade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.CharField(max_length=120, verbose_name='Solicitação')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo da Solicitação ')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data da Abertura')),
                ('data_atendimento', models.DateTimeField(verbose_name='Data do Atendimento')),
                ('data_encerramento', models.DateTimeField(verbose_name='Data do Encerramento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendente', to='website.usuario')),
                ('servico', models.ManyToManyField(to='website.servico')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='website.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ocorrencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.usuario')),
            ],
        ),
    ]
