# Generated by Django 5.1.7 on 2025-03-06 21:51

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('instrutor', models.CharField(max_length=100, verbose_name='Instrutor')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('prioridade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('template', models.FileField(blank=True, null=True, upload_to='templates/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('filter', models.CharField(blank=True, default='.filter-outros', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('url_latters', models.URLField(max_length=100, verbose_name='URL')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('url_twitter', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL twitter')),
                ('url_facebook', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL facebook')),
                ('url_instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL Instagram')),
                ('url_linkedin', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL linkedin')),
                ('foto', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='foto')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Post')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.CharField(max_length=120, verbose_name='Solicitação')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo da Solicitação ')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data da Abertura')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Atendimento')),
                ('data_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Encerramento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendente', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ManyToManyField(to='website.servico')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('vigencia_inicio', models.DateField(verbose_name='Início da vigência ')),
                ('vigencia_fim', models.DateField(verbose_name='FIM da vigência ')),
                ('numero_parcelas', models.IntegerField(default=12, verbose_name='Número de parcelas')),
                ('objetivo_proposto', models.TextField(verbose_name='Objetivo proposto')),
                ('resultado_esperado', models.TextField(verbose_name='Resultados esperados ')),
                ('objetivo_proposto_obj', models.TextField(verbose_name='Objetivos propostos')),
                ('dia_entrega', models.IntegerField(default=0, verbose_name='Dia do mês da entrega')),
                ('template', models.FileField(blank=True, null=True, upload_to='templates/')),
                ('status', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Em elaboração', max_length=100, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('template_default', models.BooleanField(default=False, verbose_name='Usar template padrão')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('autores', models.CharField(max_length=100, verbose_name='Autores')),
                ('artigo_upload', models.FileField(blank=True, null=True, upload_to='artigos/')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Post')),
                ('categoria', models.ManyToManyField(to='website.categoria_publicacao')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos_principais', tinymce.models.HTMLField()),
                ('principais_obstaculos', tinymce.models.HTMLField()),
                ('resultados_esperados_alcancados', tinymce.models.HTMLField()),
                ('informacao_adicional', tinymce.models.HTMLField()),
                ('conclusoes', tinymce.models.HTMLField()),
                ('data_vigencia', models.DateField(blank=True, null=True, verbose_name='Data de vigencia')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de assinatura')),
                ('assinatura', models.FileField(blank=True, null=True, upload_to='assinaturas/')),
                ('doc', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projetorelatorio')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Data')),
                ('url', models.URLField(max_length=100, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem 3')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('type', models.ManyToManyField(to='website.tipoprojeto')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ocorrencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', tinymce.models.HTMLField()),
                ('informacao_adicional', models.TextField(blank=True, null=True, verbose_name='Informações adicionais')),
                ('data_vigencia', models.DateField(blank=True, null=True, verbose_name='Data de vigencia')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de assinatura')),
                ('parcela', models.IntegerField(default=1, verbose_name='Parcela')),
                ('assinatura', models.FileField(blank=True, null=True, upload_to='assinaturas/')),
                ('doc', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projetorelatorio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('projeto', 'parcela'), name='unica_parcela', violation_error_message='Já existe um relatório para esta parcela')],
            },
        ),
    ]
