# Generated by Django 4.0.5 on 2022-07-26 22:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('prioridade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('filter', models.CharField(blank=True, default='.filter-outros', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('autores', models.CharField(max_length=100, verbose_name='Autores')),
                ('artigo_upload', models.FileField(blank=True, null=True, upload_to='artigos/')),
                ('post_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data do Post')),
                ('categoria', models.ManyToManyField(to='website.categoria_publicacao')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Data')),
                ('url', models.URLField(max_length=100, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem 3')),
                ('type', models.ManyToManyField(to='website.tipoprojeto')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.CharField(max_length=120, verbose_name='Solicitação')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo da Solicitação ')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data da Abertura')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Atendimento')),
                ('data_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Encerramento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendente', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ManyToManyField(to='website.servico')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ocorrencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('url_latters', models.URLField(max_length=100, verbose_name='URL')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('url_twitter', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL twitter')),
                ('url_facebook', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL facebook')),
                ('url_instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL Instagram')),
                ('url_linkedin', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL linkedin')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='foto')),
                ('post_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data do Post')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
