# Generated by Django 4.0.5 on 2022-07-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria_publicacao',
            name='description',
        ),
    ]
