# Generated by Django 4.0.5 on 2022-07-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_categoria_publicacao_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='foto'),
        ),
    ]
