# Generated by Django 4.0.5 on 2022-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status'),
        ),
    ]
