# Generated by Django 4.0.5 on 2022-06-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_atendimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Atendimento'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Encerramento'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo da Solicitação '),
        ),
    ]
