# Generated by Django 4.0.5 on 2022-07-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_colaborador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='foto'),
        ),
    ]
