# Generated by Django 4.0.5 on 2022-07-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_ocorrencia_data_atendimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Data')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('type', models.ManyToManyField(to='website.tipoprojeto')),
            ],
        ),
    ]
