# Generated by Django 4.0.5 on 2022-07-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_tipoprojeto_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem 1'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem 2'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem 3'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='url',
            field=models.URLField(max_length=100, verbose_name='URL'),
        ),
    ]
