# Generated by Django 4.1 on 2022-09-01 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_projeto_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('vigencia_inicio', models.DateField(verbose_name='Início da vigência ')),
                ('vigencia_fim', models.DateField(verbose_name='FIM da vigência ')),
                ('numero_parcelas', models.IntegerField(default=1, verbose_name='Número de parcelas')),
                ('objetivo_proposto', models.TextField(verbose_name='Objetivo proposto')),
                ('objetivo_proposto_obj', models.TextField(verbose_name='Objetivo proposto')),
                ('template', models.FileField(blank=True, null=True, upload_to='templates/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
