# Generated by Django 4.0.5 on 2022-07-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_projeto_image1_projeto_image2_projeto_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente'),
        ),
    ]
