# Generated by Django 4.0.5 on 2022-09-02 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_projeto_user'),
    ]

    operations = [

    ]
