# Generated by Django 4.0.5 on 2022-07-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_projeto_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprojeto',
            name='filter',
            field=models.CharField(blank=True, default='.filter-outros', max_length=30, null=True),
        ),
    ]
