# Generated by Django 4.0.5 on 2022-09-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_projetorelatorio_dia_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='assinatura',
            field=models.FileField(blank=True, null=True, upload_to='assinaturas/'),
        ),
    ]
