# Generated by Django 4.0.5 on 2022-07-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_tipoprojeto_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('url_latters', models.URLField(max_length=100, verbose_name='URL')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('url_twitter', models.URLField(max_length=100, verbose_name='URL twitter')),
                ('url_facebook', models.URLField(max_length=100, verbose_name='URL facebook')),
                ('url_instagram', models.URLField(max_length=100, verbose_name='URL Instagram')),
                ('url_linkedin', models.URLField(max_length=100, verbose_name='URL linkedin')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('autores', models.CharField(max_length=100, verbose_name='Autores')),
            ],
        ),
    ]
