# Generated by Django 4.0.5 on 2022-07-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_colaborador_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='url_facebook',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='URL facebook'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='url_instagram',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='URL Instagram'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='url_linkedin',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='URL linkedin'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='url_twitter',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='URL twitter'),
        ),
    ]
