# Generated by Django 4.0.5 on 2022-09-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_relatorio_data_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
