# Generated by Django 4.0.5 on 2022-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_relatorio_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetorelatorio',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Em elaboração', max_length=100, verbose_name='Status'),
        ),
    ]
