# Generated by Django 4.0.5 on 2022-09-04 23:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_projetorelatorio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='resultado',
            field=tinymce.models.HTMLField(),
        ),
    ]
