# Generated by Django 4.0.5 on 2022-09-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_relatorio_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
