# Generated by Django 4.0.5 on 2022-09-14 12:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_projeto_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos_principais', tinymce.models.HTMLField()),
                ('principais_obstaculos', tinymce.models.HTMLField()),
                ('resultados_esperados_alcancados', tinymce.models.HTMLField()),
                ('informacao_adicional', tinymce.models.HTMLField()),
                ('conclusoes', tinymce.models.HTMLField()),
                ('data_vigencia', models.DateField(blank=True, null=True, verbose_name='Data de vigencia')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de assinatura')),
                ('assinatura', models.FileField(blank=True, null=True, upload_to='assinaturas/')),
                ('doc', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projetorelatorio')),
            ],
        ),
    ]
