# Generated by Django 4.0.5 on 2022-09-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_relatoriofinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('template', models.FileField(blank=True, null=True, upload_to='templates/')),
            ],
        ),
    ]
