# Generated by Django 4.0.5 on 2022-09-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_templates'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relatorio',
            constraint=models.UniqueConstraint(fields=('projeto', 'parcela'), name='unica_parcela'),
        ),
    ]
