# Generated by Django 4.1.1 on 2022-09-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_relatorio_unica_parcela'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relatorio',
            name='unica_parcela',
        ),
        migrations.AddConstraint(
            model_name='relatorio',
            constraint=models.UniqueConstraint(fields=('projeto', 'parcela'), name='unica_parcela', violation_error_message='Já existe um relatório para esta parcela'),
        ),
    ]
