# Generated by Django 4.1.1 on 2022-09-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_projetorelatorio'),
        ('website', '0018_relatorio_unica_parcela'),
    ]

    operations = [
    ]
