# Generated by Django 4.1 on 2022-09-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_projetorelatorio'),
        ('website', '0019_remove_relatorio_unica_parcela_and_more'),
    ]

    operations = [
    ]
