# Generated by Django 4.1 on 2022-09-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_merge_20220930_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetorelatorio',
            name='dia_entrega',
            field=models.IntegerField(default=0, verbose_name='Dia do mês da entrega'),
        ),
        migrations.AddField(
            model_name='projetorelatorio',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Em elaboração', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projetorelatorio',
            name='numero_parcelas',
            field=models.IntegerField(default=12, verbose_name='Número de parcelas'),
        ),
    ]
