# Generated by Django 4.1 on 2022-09-30 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_projetorelatorio_dia_entrega_projetorelatorio_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetorelatorio',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='projetorelatorio',
            name='template_default',
            field=models.BooleanField(default=False, verbose_name='Usar template padrão'),
        ),
    ]
