# Generated by Django 4.1 on 2022-09-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_projetorelatorio_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetorelatorio',
            name='data_criacao',
        ),
    ]
