# Generated by Django 4.1 on 2022-09-30 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_projetorelatorio_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetorelatorio',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de criação'),
        ),
    ]
