# Generated by Django 4.1.1 on 2022-10-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_rename_data_criacao1_projetorelatorio_data_criacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='data',
            new_name='date',
        ),
    ]
