# Generated by Django 4.1.1 on 2022-10-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_rename_data_historico_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='data_atual',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='data_entrega',
        ),
    ]
